added stripeAccount field to nonprofit collection
GTBitsOfGood/gen-soln pull request #132
Opened 2020-09-13 16:47 UTC by Cullen101

added stripeAccount field on types.ts, nonprofit.js, and nonprofit.ts

2020-09-13 17:50 UTC, KoolCards approved these changes

2020-09-13 17:52 UTC, PC98 requested changes
Let's hold off on merging this, I will add some feedback soon

2020-09-13 18:31 UTC, PC98 reviewed
Can you also write a migration script? In general, every schema change for models that already have data in our DB should be accompanied by a migration script. You will have to:
* Create a new migration script, `yarn dev:db:migrate migrate-nonprofits-add-stripe-account` or whatever name you think is appropriate.
* Have a look at existing scripts in `server/migrations` to implement the migration `up` and migration `down` functions. In `up`, you will want to update each document in the `"nonprofits"` collection to have a `stripeAccount` field; for now, you can use dummy values or an empty string for `stripeAccount`. In `down` you will do the opposite - remove this field from all documents.

2020-09-13 18:31 UTC, PC98 commented on utils/types.ts
> +  stripeAccount: string;
Question: will the `stripeAccount` field be confidential?

Should we be sending this data to our front-end? If not, can you remove this attribute from this type (the type here represents all the fields the front-end can access) and modify the `getNonprofitById()` server action to exclude this field when returning data to the front-end?

2020-09-13 18:36 UTC, KoolCards commented on utils/types.ts
> +  stripeAccount: string;
The workflow for creating a new stripe account is that when a nonprofit onboards, they'll need to send their stripeAccount id from the frontend to the backend. However, I think you're right we actually probably shouldn't be sending this back to the fronted.

2020-09-13 18:37 UTC, KoolCards commented
> Can you also write a migration script? In general, every schema change for models that already have data in our DB should be accompanied by a migration script. You will have to:
> 
> * Create a new migration script, `yarn dev:db:migrate migrate-nonprofits-add-stripe-account` or whatever name you think is appropriate.
> * Have a look at existing scripts in `server/migrations` to implement the migration `up` and migration `down` functions. In `up`, you will want to update each document in the `"nonprofits"` collection to have a `stripeAccount` field; for now, you can use dummy values or an empty string for `stripeAccount`. In `down` you will do the opposite - remove this field from all documents.

Ahh ok. So I had assumed that since we weren't updating the stripeAccount field of existing nonprofit collections that we wouldn't need to create a migration script. However, I guess ur saying that it's best to have dummy values as the stripeAccount for now.

2020-09-13 18:39 UTC, PC98 commented on utils/types.ts
> +  stripeAccount: string;
Thanks for confirming -- we should still remove it from the type as well since the front-end uses this type to assume the shape of the returned data from the back-end. I will open a PR to update the comments in this file to make this clear.

2020-09-13 20:13 UTC, KoolCards commented on server/actions/nonprofit.ts
> +  const nonprofit = await Nonprofit.findOne({ _id }, { donations: 0 })
Last thing, you can specify the field to exclude as the projection parameter in the mongoose query. Can you modify this so that we exclude stripeAccount the same way we exclude donations?

2020-09-13 20:19 UTC, PC98 commented on server/migrations/20200913194527-migrate-nonprofits-add-stripe-account.ts
> +    .updateMany({ _id: { $in: nonprofits } }, { $set: { stripeAccount: "" } });
Just do:
```
db
    .collection("nonprofits")
    .update(
      { },
      { $set: { stripeAccount: "" } },
      { multi: true }
    );
```
This will let you avoid hard-coding the non-profit IDs. You can also take this approach in your `down()` function

2020-09-13 20:19 UTC, PC98 commented on utils/types.ts
> +  stripeAccount: string;
@Cullen101 I think you forgot to delete this

2020-09-13 20:20 UTC, PC98 reviewed
You will also have a conflict with the develop branch -- let me know if you need help resolving that!

2020-09-13 20:23 UTC, KoolCards commented on server/migrations/20200913194527-migrate-nonprofits-add-stripe-account.ts
> +    .updateMany({ _id: { $in: nonprofits } }, { $set: { stripeAccount: "" } });
I thought we'd only want to update only the current 3 nonprofits with the migration script because the schema change will automatically update any future nonprofits we add to the db. That's why it's hardcoded, but I guess either way works.

2020-09-13 20:32 UTC, PC98 commented on server/migrations/20200913194527-migrate-nonprofits-add-stripe-account.ts
> +    .updateMany({ _id: { $in: nonprofits } }, { $set: { stripeAccount: "" } });
Yeah, ideally we shouldn't hardcode. Right now I am thinking that all the "seed" migration scripts won't run on prod DB, but all the "migrate" migration scripts will. Since this script will run on prod DB, here is what we can to ensure that if a document already has a `stripeAccount`, we don't set it to the empty string:
```
await db
  .collection("nonprofits")
  .update(
    { stripeAccount: { $exists: false } },
    { $set: { stripeAccount: [] } },
    { multi: true }
  );
```
And similar changes to `down`.

We will *most* of the data to our prod DB using server actions triggered by API calls.

2020-09-15 23:22 UTC, KoolCards commented
@PC98 re-requesting your review before merging. We made stripeAccount an optional field in the Nonprofit type, as stripeAccount has to be sent from frontend to backend when onboarding in the Nonprofit object, but never from backend to frontend.

2020-09-15 23:39 UTC, PC98 approved these changes
Tbh you can still omit this from the `Nonprofit` interface imo, since we might not end up using the interface in the form when collecting data and seding it to the backend (though we won't know for sure until the form code is actually implemented).

I just don't any future front-end devs confused and think that they can access the `stripeAccount` from a Nonprofit type even though that's not true/the DB never returns it.

2020-09-16 00:09 UTC, PC98 commented on server/actions/nonprofit.ts
>  }: NonprofitType) {
If line 19 was throwing a TS error when you removed `stripeAccount`, you can just use `NextApiRequest["body"]` instead of `NonprofitType`; I don't think annotating with `NonprofitType` was giving us anything nice.

2020-09-16 00:37 UTC, merged