Add actions createStripeAccount() and linkStripeAccount()
GTBitsOfGood/gen-soln pull request #138
Opened 2020-09-13 23:08 UTC by ML-Chen

#103

2020-09-13 23:28 UTC, PC98 requested changes

2020-09-13 23:28 UTC, PC98 commented on server/actions/nonprofit.ts
> +import config from "../../config";
nit: `import config from "config";`

2020-09-13 23:28 UTC, PC98 commented on server/actions/nonprofit.ts
> +});
Can you put this code in a function, perhaps in `server/index.js`? I want to avoid code duplication since `donation.ts` also creates a Stripe object with this `apiVersion`

2020-09-13 23:28 UTC, PC98 commented on server/actions/nonprofit.ts
> +  .catch(err => console.log(err));
should this be here? I think you meant to use these lines for testing purposes only.

2020-09-13 23:28 UTC, PC98 commented on server/actions/nonprofit.ts
> +    // Placeholder URLs
Can you put a `TODO` in your comment, and potentially create a task to track this.

Also just so I understand things correctly, what's the URL that we actually want to use for `refresh_url` and `return_url`?

2020-09-13 23:28 UTC, PC98 commented on config.ts
> +    "http://localhost:3000",
I think the `|| "http://localhost:3000"` is redundant (assuming that our URLs are not empty or null/undefined)

2020-09-13 23:28 UTC, PC98 commented on .env.development
> +DEV_BASE_URL=http://localhost:3000
What do you think of adding `PROD_BASE_URL` as well, since it's not really a "secret". You could either add `PROD_BASE_URL` in a new `.env.production` file, or to simplify things, you can rename this file to `.env` and add `PROD_BASE_URL` here as well.

2020-09-13 23:42 UTC, ML-Chen commented on config.ts
> +    "http://localhost:3000",
That's true, but I didn't want to have to write `/* eslint-disable-next-line @typescript-eslint/no-non-null-assertion */` each time we use it.

2020-09-13 23:43 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +  .catch(err => console.log(err));
I've just pushed a commit that removes this part.

2020-09-13 23:45 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +});
A function to construct a Stripe object with that apiVersion? Or do we want a stripe singleton?

2020-09-13 23:46 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +    // Placeholder URLs
I'm not sure what the URL is supposed to be. @KoolCards ?

2020-09-13 23:47 UTC, ML-Chen commented on .env.development
> +DEV_BASE_URL=http://localhost:3000
What is the PROD_BASE_URL supposed to be? Should I just write `PROD_BASE_URL=` with no value?

2020-09-13 23:49 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +import config from "../../config";
Fixed

2020-09-13 23:50 UTC, KoolCards commented on server/actions/nonprofit.ts
> +    // Placeholder URLs
We don't have an actual `refresh_url` and `return_url` yet because these are supposed to be the urls to our nonprofit onboarding form (which doesn't exist right now). Right now, we just have it redirect to the donate page.

2020-09-14 00:30 UTC, PC98 commented on .env.development
> +DEV_BASE_URL=http://localhost:3000
Won't `PROD_BASE_URL` just be where we have our web app deployed? `https://bog-gen-soln.vercel.app`?
So yeah, you can either add `PROD_BASE_URL=https://bog-gen-soln.vercel.app` to a `.env.production` file, or to keep things simpler rename this file to `.env` and add it here (I prefer the latter).

2020-09-14 00:52 UTC, PC98 commented on config.ts
> +    "http://localhost:3000",
Tbh I don't imagine that we will use `baseUrl` that much; our codebase hadn't needed it so far 🙂 
Also as an FYI, you can also use `/* eslint-disable @typescript-eslint/no-non-null-assertion */` to completely disable the lint rule in a block of text and enable it after the block: `/* eslint-enable @typescript-eslint/no-non-null-assertion */` 

I just don't like hardcoding `http://localhost:3000` twice since if we ever change the default port, it's possible someone updates the .env file but forgets to update `config.ts`.

2020-09-14 00:52 UTC, PC98 commented on server/actions/nonprofit.ts
> +});
Is there a way to easily implement a singleton in JS? I am not that familiar, but if you know a way that is not hacky then sure go for it. Otherwise, a simple function that creates and returns a Stripe object should do.

2020-09-14 00:53 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +    // Placeholder URLs
Added a comment so now it looks like this:
```ts
  const accountLink = await stripe.accountLinks.create({
    account: accountId,
    /* TODO: These are placeholder URLs. They should be replaced with the URL of
         our nonprofit on-boarding form once we create that. */
    refresh_url: config.baseUrl + config.pages.donate(defaultNonprofitId),
    return_url: config.baseUrl + config.pages.donate(defaultNonprofitId),
    type: "account_onboarding"
  });
```

2020-09-14 00:56 UTC, PC98 commented on server/actions/nonprofit.ts
> +    // Placeholder URLs
Ah I see. But we are not re-directing to that particular non-profit's donate page here, just to the "default" non-profit's? I would recommend either re-directing to the particular non-profit's donation page or to the index page (given by the base URL).

I don't want to introduce further usage of `getDefaultNonprofitId()`; this function will go away when our index page has been built.

2020-09-14 00:57 UTC, PC98 commented on server/actions/nonprofit.ts
> +    // Placeholder URLs
@ML-Chen Thanks for adding the TODO -- bonus points if you want to expand your TODO to mention that the URLs eventually need to be replaced with the nonprofit onboarding form URL

2020-09-14 00:58 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +});
By singleton I meant instantiating the Stripe object once in index.js and importing it into other files. I think I was using the word "singleton" wrong.

2020-09-14 01:00 UTC, PC98 commented on server/actions/nonprofit.ts
> +});
No I think I understood what you meant. I think the problem is that if you do this in `index.js`:
```
export const stripe = new Stripe(config.stripe.secret_key, {
  apiVersion: "2020-03-02"
});
```
this code will run whenever someone imports anything from `index.js`, even if they are not importing the `stripe` object (which is basically all files in `server/actions`)

2020-09-14 01:01 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +    // Placeholder URLs
Okay I'll change it to this then:
```ts
  const accountLink = await stripe.accountLinks.create({
    account: accountId,
    /* TODO: These are placeholder URLs. They should be replaced with the URL of
         our nonprofit on-boarding form once we create that. */
    refresh_url: config.baseUrl,
    return_url: config.baseUrl,
    type: "account_onboarding"
  });
```

2020-09-14 01:05 UTC, ML-Chen commented on config.ts
> +    "http://localhost:3000",
What about this?
```ts
  baseUrl: (isDevEnv
    ? process.env.DEV_BASE_URL
    : process.env.PROD_BASE_URL) as string,
```

2020-09-14 01:08 UTC, ML-Chen commented on .env.development
> +DEV_BASE_URL=http://localhost:3000
So would that include merging .env.development.local and .env.local?

2020-09-14 01:14 UTC, PC98 commented on config.ts
> +    "http://localhost:3000",
This will further hide the error? Since I think `null as string` will just cast the string to `"null"`. Whereas with `/* eslint-disable @typescript-eslint/no-non-null-assertion */` we can track where the potential null casting is taking place.

2020-09-14 01:15 UTC, PC98 commented on .env.development
> +DEV_BASE_URL=http://localhost:3000
I think `.env.development.local` and `.env.local` can remain unchanged.

2020-09-14 01:28 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +});
So https://stackoverflow.com/questions/37325667/does-es6-module-importing-execute-the-code-inside-the-imported-file an imported file is only supposed to be run once even if it is imported multiple times. When I have a console.log statement in nonprofit.ts, it runs twice the first time I load a page after build, and then once for every subsequent page load. Right now for testing purposes I have a function from nonprofit.ts imported into three files.

2020-09-14 01:37 UTC, ML-Chen commented on .env.development
> +DEV_BASE_URL=http://localhost:3000
So then `.env` is for both production and development environment variables that are not secret, and `.env.local` is for production secrets? That seems a little confusing but I guess it's alright.

2020-09-14 01:41 UTC, PC98 commented on .env.development
> +DEV_BASE_URL=http://localhost:3000
Yeah, we need at least two env files. One for secrets and one for non-secrets.

We can combine `.env.local` and `.env.development.local` but this will be more involved -- the yarn secrets scripts will have to be modified and we will have to ask all devs to delete their local copy of `.env.development.local`

2020-09-14 01:46 UTC, PC98 commented on server/actions/nonprofit.ts
> +});
> Right now for testing purposes I have a function from nonprofit.ts imported into three files.

Not sure what you mean.
If it is being run multiple times, I assume you will be taking the approach of creating a function that constructs the Stripe object?

2020-09-14 01:47 UTC, ML-Chen commented on config.ts
> +    "http://localhost:3000",
What about
```ts
baseUrl: (isDevEnv ? process.env.DEV_BASE_URL : process.env.PROD_BASE_URL)!
```

Although now that I'm not concatenating the baseUrl anymore, TypeScript doesn't care that it's `string | undefined`

2020-09-14 01:50 UTC, PC98 commented on config.ts
> +    "http://localhost:3000",
Sure, `baseUrl: (isDevEnv ? process.env.DEV_BASE_URL : process.env.PROD_BASE_URL)!` is fine. Or if TS doesn't care, you can just skip this and be consistent with how other variables in `config` are defined.

2020-09-14 02:00 UTC, ML-Chen commented on server/actions/nonprofit.ts
> +});
It seems that when I have a console.log statement in index.js, it prints every time I go to a different page, so it seems that yeah it does get run an awful lot of times.

2020-09-14 02:35 UTC, ML-Chen commented on .env.development
> +DEV_BASE_URL=http://localhost:3000
I've made changes that should resolve this and your other comments. Please see the new commit.

2020-09-14 02:42 UTC, PC98 approved these changes
Thanks for iterating on this!

2020-09-14 02:56 UTC, merged